"""The laws of the game in words, with every number: what bot writers read (RULES.md, `botkit.py rules`) and what
the LLM teams are told. Generated from the rules object, so it always matches the engine."""
from __future__ import annotations

from .config import Rules


def rules_text(r: Rules, audience: str = "team") -> str:
    """The rules as told to a controller. audience="team": one model orders the whole team (the ACTIONS block ends with the
    team response format); "coach" / "player": the same rules and action vocabulary without the team response format, which
    the two-tier prompts replace with their own."""
    free_run = (" (they can't enter that area but are otherwise free to run, around it or anywhere else: only the taker and the man on the mark stand still)"
                if getattr(r, "protected_area_free_run", False) else "")              # (engine v1's text had no such note)
    reflex = (f"Any player within {r.loose_ball_reflex_radius:.0f} m of a loose ball, or within {r.flight_reflex_radius:.0f} m of where a kick will land, runs to it and contests it automatically, whether or not you ordered it (a defender arriving this way spoils if an attacker is also there, and marks only if alone); "
              "ATTEMPT_POSSESSION / ATTEMPT_MARK / SPOIL are how you send a player to the ball." if r.auto_contest else
              "Players only contest a ball when ordered to (ATTEMPT_POSSESSION / ATTEMPT_MARK / SPOIL).")
    bounce = (f"- RUNNING WITH THE BALL: a carrier must bounce the ball every {r.run_limit_m:.0f} m; the bounce is automatic and succeeds with probability about "
              f"{r.bounce_base:.2f} + 0.45 x ground_ball_skill minus up to {r.bounce_speed_penalty:.2f} when running at top speed. A fumbled bounce is a loose ball just ahead of the runner. The state shows how far the carrier has run since the last bounce.\n"
              if r.run_limit_m > 0 else "")
    timing = (f"- You give orders once every {r.decision_interval:.0f} simulated second(s), and again straight after a kick (while the ball is in the air, with its landing point and time to land in the state), a possession change, mark, spill, fumbled bounce, free kick, throw-in or kick-in "
              f"(never more often than every {r.min_decision_gap:.1f} s). The state field decision_reason says why you are being asked." if r.event_decisions else
              f"- You give orders once every {r.decision_interval:.0f} simulated second(s).")
    opening = {"team": f"You control one team of {r.n_per_team} in a simplified {r.n_per_team}-a-side Australian Rules football match on an oval.",
               "coach": f"You coach one team of {r.n_per_team} in a simplified {r.n_per_team}-a-side Australian Rules football match on an oval; your players are independent agents who read your plan.",
               "player": f"You are one player in a simplified {r.n_per_team}-a-side Australian Rules football match on an oval."}[audience]
    response = ('Respond with exactly this JSON: {"intent": "<one or two sentences on what you are trying to do and why>", "actions": [ ... ]}. ' if audience == "team" else "")
    actions_header = ("ACTIONS (JSON). Each action names one of your players. A player not mentioned keeps moving to their previous MOVE target (if any) and has no ball order."
                      if audience == "team" else "ACTIONS a player can take (JSON; the exact response format for you is given further down).")
    return f"""{opening}

GROUND AND SCORING
- The ground is an oval {r.length:.0f} m from goal line to goal line (x from 0 to {r.length:.0f}) and {r.width:.0f} m wide at the centre (y from {-r.width/2:.1f} to {r.width/2:.1f}); it narrows towards the ends. Each goal line is the flat {2*r.behind_half_width:.1f} m end of the oval: goal posts at y = -{r.goal_half_width} and +{r.goal_half_width}, behind posts at y = -{r.behind_half_width} and +{r.behind_half_width}. The centre is ({r.length/2:.0f}, 0).
- Team A scores at x = {r.length:.0f} and defends x = 0. Team B scores at x = 0 and defends x = {r.length:.0f}.
- A ball kicked by a team that crosses the goal line it attacks between the goal posts is a goal ({r.goal_points} points). A ball crossing between a goal post and a behind post is a behind ({r.behind_points} point); so is any ball a team puts over its own goal line between the behind posts, or a handball through the goal posts. There is no separate shooting action: a shot is a kick aimed at or beyond the goal line, and the ball's actual flight decides.
- After a behind the conceding team kicks in from the top of its goal square with the opponents held {r.kick_in_clearance:.0f} m away. {'After a goal the game restarts with a ball-up at the centre and the score stands.' if r.end_on == 'time' else 'A goal ends the episode.'} The episode ends when the clock reaches {r.episode_seconds:.0f} s.
- The episode starts (and restarts after a goal) with a ball-up at the centre: the ball is loose with one midfielder from each side beside it and the other midfielders in the centre square; defenders start spread across their defensive half and forwards across their attacking half, a quarter of the ground from goal.

TIME
{timing} Orders persist until you change them. Physics runs continuously between your decisions.

PLAYERS
- Each player has a role (midfielder, defender or forward, given in the state) and attributes in [0, 1]: speed, acceleration, kick_power, kick_accuracy, handball_power, handball_accuracy, marking_skill, ground_ball_skill, tackling_skill (also used to resist tackles). The role only sets the typical attribute profile, always check the actual numbers: midfielders are the fastest and best at ground balls, handballs and tackling with average kicks and marks; forwards are slower but have the longest and most accurate kicks and the best marking, especially under pressure; defenders are strong in the air (marking and spoiling), the best tacklers, with good long kicks. Where anyone plays is entirely up to you. Top speed ranges 6.5-9 m/s. Kick range at full power ranges {r.kick_min_distance_scale:.0f}-{r.kick_max_distance_scale:.0f} m with kick_power (scaled to this ground); handball range {r.handball_min_distance_scale:.0f}-{r.handball_max_distance_scale:.0f} m.
- {reflex}

BALL MECHANICS (all stochastic)
- GATHERING TIME: a disposal cannot leave until the player has held the ball for {r.min_possession_seconds:.1f} s; during that time they can be tackled.
- KICK: the ball travels in the air towards the target at ground speed ~{r.kick_ground_speed:.0f} m/s (flight time about {r.kick_flight_base:.1f} s + distance/{r.kick_ground_speed:.0f}). The requested distance is capped at kick range x power. A target further than that is a bomb: the ball can be sent up to {r.kick_bomb_scale:.1f}x the range, but the error grows up to {1 + r.kick_bomb_error_gain:.0f}x along the way (a full bomb lands roughly anywhere within tens of metres, so it is a lottery, not a pass). Pressure shortens a kick by {100 * r.pressure_distance_loss:.0f} % per unit of pressure (pressure is 0-2), and a kick never travels further than the kicker's reach: scatter can drop it short or wide, never carry it longer. The landing point has a random error that grows in proportion to distance (roughly a fixed angle, so a 50 m kick misses by about 2.5 times as much as a 20 m kick), with the kicker's running speed and with pressure from nearby opponents, and shrinks with kick_accuracy. A shot straight in front by an average kicker at rest is a goal about 84 % of the time from 20 m, 68 % from 30 m, 55 % from 40 m and 46 % from 50 m. A ball in flight can only be contested near the ground (start and end of the flight). Players keep moving while the ball is in the air: to kick to a moving teammate you must aim at where they will be when the ball arrives (their position plus their velocity times the flight time), not where they are now.
- HANDBALL: shorter, faster, flatter, more accurate; error grows with distance, running speed and pressure. A handball can be intercepted and can never be marked. The same aiming-ahead applies; target_player aims a little ahead of the named teammate automatically.
- MARK: if a KICK travels at least {r.mark_min_kick_distance:.0f} m and a player is within {r.mark_radius:.0f} m of where it comes down, that player may mark it. An unpressured player at the landing point marks about 95 % of the time; the chance falls with distance from the landing point and sharply with close pressure (an opponent within a metre roughly halves it for an average marker, two opponents close in cut it to about a third), and marking_skill is what resists that pressure (a 0.9 marker keeps about two thirds of their chance where a 0.5 marker keeps half); several players may contest and one may win, the one nearest the landing point being favoured. Kicks shorter than {r.mark_min_kick_distance:.0f} m can be caught but never marked.
- SPOIL: a player ordered to SPOIL runs to where a kick will come down and tries to punch it away instead of marking; a spoil succeeds with {r.spoil_skill_factor:.0%} of the corresponding mark chance (same distance and pressure effects), and turns the ball into a loose ball travelling away from the spoiler. Only kicks can be spoiled.
- SET PLAYS (marks and free kicks): if an opponent is within {r.man_on_mark_radius:.0f} m, the player who marks or is awarded a free kick is placed {r.set_play_retreat:.0f} m behind the mark, the nearest opponent is put on the mark and must stand still, and all other opponents are kept at least {r.protected_area:.0f} m from the taker{free_run}. The taker cannot be tackled and feels no pressure from the man on the mark, so a kick from the set position is as accurate as an unpressured kick. The taker has two options: kick from the set position (KICK), or play on (a MOVE order, a handball, or running off the spot), which frees the man on the mark and returns to normal play immediately. If the taker does nothing for {r.set_play_seconds:.0f} s, play on is called. If no opponent is within {r.man_on_mark_radius:.0f} m when the mark or free is taken there is no set play at all: the player simply has the ball and plays on. A shot aimed at the goal line is carried a few metres through it, so aim at the goal, not short of it. Kicks shorter than {r.mark_min_kick_distance:.0f} m do not create a set play.
- LOOSE BALL: when the ball is on the ground it rolls and slows. Any player within {r.loose_ball_reflex_radius:.0f} m of a loose ball goes for it whatever their order, and a KICK or HANDBALL order given to a player who does not yet hold the ball also sends them to get it. Players within {r.possession_radius:.0f} m may gain possession; a player standing over the ball picks it up almost at once, a player sprinting past it usually does not; the chance depends on ground_ball_skill, distance to the ball, pressure and how fast they are running. Several contestants are resolved probabilistically, not by who is closest.
- ENERGY: every player has energy 0-1 (shown in the state), starting full. Running above {r.energy_sprint_fraction:.0%} of top speed (a sprint) drains it: an average player (endurance 0.7) empties in about {1.2 * r.energy_sprint_seconds:.0f} s of continuous sprinting, less for low endurance and more for high; a steady run drains at roughly 70 % of that rate. Below {r.energy_recover_fraction:.0%} of top speed (a jog, standing still, holding a set play, standing the mark) it recovers: standing still is fastest (empty to full in {r.energy_recover_seconds:.0f} s), a jog recovers at a bit under half that rate. In between (a run) it holds. A tired player is slower: top speed and acceleration are scaled by {r.energy_speed_floor:.0%} + {1 - r.energy_speed_floor:.0%} x energy, so half energy means three-quarter pace and empty means half pace. MOVE takes a pace: sprint (full speed), run (default, {r.pace_run:.0%} of top speed, sustainable) or jog ({r.pace_jog:.0%}, recovers). Contesting a ball, tackling and the reflexes always sprint. Sprint when arriving first matters; jog when it does not; a team that sprints everywhere is at three-quarter pace by the last minute.
{bounce}- TACKLE: a player ordered to TACKLE runs at the named opponent and, when within {r.tackle_radius:.1f} m of an unprotected ball carrier, attempts tackles continuously. Success depends on tackling_skill versus the carrier's tackling_skill, distance and closing speed. If the carrier had prior opportunity (held the ball for at least {r.holding_the_ball_seconds:.0f} s, or run more than {r.prior_opportunity_m:.0f} m with it) the tackler is awarded a free kick (a set play); otherwise the ball spills loose nearby. Running with the ball is fast but a tackle after 5 m of running costs a free kick.
- OUT OF BOUNDS: a kick or handball that crosses the boundary in the air ("out on the full") is a free kick (set play) to the nearest opponent at the spot. A ball that rolls, spills or is spoiled over the boundary is thrown back in about {r.throw_in_distance:.0f} m from the spot as a loose ball. Play continues in both cases.
- PRESSURE: every opponent contributes exp(-(distance/{r.pressure_scale:.0f} m)^2) (about 0.7 at 3 m, 0.1 at 8 m), summed and capped at {r.pressure_cap:.0f}. Pressure worsens kicks, handballs, marks and ground-ball gathers.

{actions_header}
- {{"player": "A1", "action": "MOVE", "target": [x, y], "pace": "run"}}  pace is optional: "sprint" | "run" (default) | "jog"; see ENERGY.  run to the point and stop there.
- {{"player": "A1", "action": "HOLD"}}  stop.
- {{"player": "A1", "action": "KICK", "target": [x, y], "power": 0.0-1.0}}  executes as soon as the player holds the ball (this decision only).
- {{"player": "A1", "action": "HANDBALL", "target": [x, y], "power": 0.0-1.0}}  or {{"player": "A1", "action": "HANDBALL", "target_player": "A3", "power": 0.6}}.
- {{"player": "A1", "action": "ATTEMPT_POSSESSION"}}  run to the ball (or where it will land) and contest it on the ground; also chases the carrier if an opponent holds it.
- {{"player": "A1", "action": "ATTEMPT_MARK"}}  run to where the kick will land and contest the mark.
- {{"player": "B1", "action": "SPOIL"}}  run to where the kick will land and punch it away.
- {{"player": "A1", "action": "TACKLE", "opponent": "B2"}}  run at that opponent and tackle when in reach.
{response}Coordinates are in metres in the ground frame described above."""
